apiVersion: apps/v1
kind: Deployment
metadata:
  name: resort
  labels:
    app: resort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resort
  template:
    metadata:
      labels:
        app: resort
    spec:
      containers:
        - name: resort
          image: username/resort:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5